# Install script for directory: /Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/Users/erikvillegas/Development/Android/android-ndk-r7b/toolchains/arm-linux-androideabi-4.4.3/prebuilt/darwin-x86/user")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "MinSizeRel")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "0")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OGRE" TYPE FILE FILES
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/asm_math.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/Ogre.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreAlignedAllocator.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreAnimable.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreAnimation.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreAnimationState.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreAnimationTrack.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreAny.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreArchive.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreArchiveFactory.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreArchiveManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreAtomicWrappers.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreAutoParamDataSource.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreAxisAlignedBox.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreBillboard.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreBillboardChain.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreBillboardParticleRenderer.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreBillboardSet.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreBitwise.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreBlendMode.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreBone.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreBorderPanelOverlayElement.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/compilation/include/OgreBuildSettings.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreCamera.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreCodec.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreColourValue.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreCommon.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreCompositionPass.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreCompositionTargetPass.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreCompositionTechnique.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreCompositor.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreCompositorChain.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreCompositorLogic.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreCompositorInstance.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreCompositorManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreConfig.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreConfigDialog.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreConfigFile.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreConfigOptionMap.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreController.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreControllerManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreConvexBody.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreCustomCompositionPass.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreDataStream.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreDefaultHardwareBufferManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreDeflate.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreDepthBuffer.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreDistanceLodStrategy.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreDualQuaternion.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreDynLib.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreDynLibManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreEdgeListBuilder.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreEntity.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreErrorDialog.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreException.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreExternalTextureSource.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreExternalTextureSourceManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreFactoryObj.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreFileSystem.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreFont.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreFontManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreFrameListener.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreFrustum.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreGpuProgram.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreGpuProgramManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreGpuProgramParams.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreGpuProgramUsage.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreHardwareBuffer.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreHardwareBufferManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreHardwareIndexBuffer.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreHardwareOcclusionQuery.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreHardwarePixelBuffer.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreHardwareVertexBuffer.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreHeaderPrefix.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreHeaderSuffix.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreHighLevelGpuProgram.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreHighLevelGpuProgramManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreImage.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreImageCodec.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreInstanceBatch.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreInstanceBatchHW.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreInstanceBatchHW_VTF.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreInstanceBatchShader.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreInstanceBatchVTF.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreInstancedGeometry.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreInstancedEntity.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreInstanceManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreIteratorRange.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreIteratorWrapper.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreIteratorWrappers.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreKeyFrame.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreLight.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreLodListener.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreLodStrategy.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreLodStrategyManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreLog.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreLogManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreManualObject.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMaterial.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMaterialManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMaterialSerializer.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMath.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMatrix3.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMatrix4.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMemoryAllocatedObject.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMemoryAllocatorConfig.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMemoryNedAlloc.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMemoryNedPooling.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMemoryStdAlloc.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMemorySTLAllocator.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMemoryTracker.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMesh.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMeshFileFormat.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMeshManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMeshSerializer.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMeshSerializerImpl.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMovableObject.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreMovablePlane.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreNode.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreNumerics.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreOptimisedUtil.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreOverlay.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreOverlayContainer.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreOverlayElement.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreOverlayElementCommands.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreOverlayElementFactory.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreOverlayManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgrePanelOverlayElement.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreParticle.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreParticleAffector.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreParticleAffectorFactory.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreParticleEmitter.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreParticleEmitterCommands.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreParticleEmitterFactory.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreParticleIterator.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreParticleScriptCompiler.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreParticleSystem.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreParticleSystemManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreParticleSystemRenderer.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgrePass.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgrePatchMesh.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgrePatchSurface.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgrePixelCountLodStrategy.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgrePixelFormat.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgrePlane.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgrePlaneBoundedVolume.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgrePlatform.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgrePlatformInformation.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgrePlugin.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgrePolygon.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgrePose.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgrePredefinedControllers.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgrePrefabFactory.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgrePrerequisites.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreProfiler.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreProgressiveMesh.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreQuaternion.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRadixSort.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRay.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRectangle.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRectangle2D.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRenderable.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRenderObjectListener.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRenderOperation.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRenderQueue.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRenderQueueInvocation.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRenderQueueListener.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRenderQueueSortingGrouping.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRenderSystem.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRenderSystemCapabilities.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRenderSystemCapabilitiesManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRenderSystemCapabilitiesSerializer.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRenderTarget.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRenderTargetListener.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRenderTexture.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRenderToVertexBuffer.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRenderWindow.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreResource.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreResourceBackgroundQueue.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreResourceGroupManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreResourceManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRibbonTrail.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRoot.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreRotationalSpline.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSceneManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSceneManagerEnumerator.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSceneNode.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSceneQuery.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreScriptCompiler.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreScriptLexer.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreScriptLoader.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreScriptParser.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreScriptTranslator.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSearchOps.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSerializer.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreShadowCameraSetup.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreShadowCameraSetupFocused.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreShadowCameraSetupLiSPSM.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreShadowCameraSetupPlaneOptimal.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreShadowCameraSetupPSSM.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreShadowCaster.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreShadowTextureManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreShadowVolumeExtrudeProgram.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSharedPtr.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSimpleRenderable.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSimpleSpline.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSingleton.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSkeleton.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSkeletonFileFormat.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSkeletonInstance.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSkeletonManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSkeletonSerializer.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSmallVector.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSphere.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSpotShadowFadePng.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreStableHeaders.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreStaticFaceGroup.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreStaticGeometry.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreStdHeaders.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreStreamSerialiser.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreString.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreStringConverter.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreStringInterface.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreStringVector.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSubEntity.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreSubMesh.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreTagPoint.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreTangentSpaceCalc.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreTechnique.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreTextAreaOverlayElement.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreTexture.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreTextureManager.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreTextureUnitState.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreTimer.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreUnifiedHighLevelGpuProgram.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreUserObjectBindings.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreUTFString.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreVector2.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreVector3.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreVector4.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreVertexBoneAssignment.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreVertexIndexData.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreViewport.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreWindowEventUtilities.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreWireBoundingBox.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreWorkQueue.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreFreeImageCodec.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreDDSCodec.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreZip.h"
    )
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OGRE/Android" TYPE FILE FILES
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/Android/OgreConfigDialogImp.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/Android/OgreErrorDialogImp.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/Android/OgreTimerImp.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/OgreStringSerialiser.h"
    )
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OGRE/Threading" TYPE FILE FILES
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/Threading/OgreThreadDefines.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/Threading/OgreThreadHeaders.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/Threading/OgreDefaultWorkQueue.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/Threading/OgreThreadDefinesNone.h"
    "/Users/erikvillegas/Development/Android/vuforia-sdk-android-1-5-9/samples/airgames/tools/Gamekit/Ogre-1.8rc/OgreMain/include/Threading/OgreDefaultWorkQueueStandard.h"
    )
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

